# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/clarke/workspace/audio-mixer-project/ip-repo/zedboard_audio/constraints/zed_audio.xdc

# XDC: /home/clarke/workspace/audio-mixer-project/ip-repo/SoC_Design/IPs/OLED/oled_constraints.xdc

# XDC: /home/clarke/workspace/audio-mixer-project/ip-repo/pmod_controller_1.0/pmod_constraints.xdc

# Block Designs: bd/audio_mixer_project/audio_mixer_project.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_mixer_project || ORIG_REF_NAME==audio_mixer_project} -quiet] -quiet

# IP: bd/audio_mixer_project/ip/audio_mixer_project_processing_system7_0_0/audio_mixer_project_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_mixer_project_processing_system7_0_0 || ORIG_REF_NAME==audio_mixer_project_processing_system7_0_0} -quiet] -quiet

# IP: bd/audio_mixer_project/ip/audio_mixer_project_axi_gpio_0_0/audio_mixer_project_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_mixer_project_axi_gpio_0_0 || ORIG_REF_NAME==audio_mixer_project_axi_gpio_0_0} -quiet] -quiet

# IP: bd/audio_mixer_project/ip/audio_mixer_project_ps7_0_axi_periph_0/audio_mixer_project_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_mixer_project_ps7_0_axi_periph_0 || ORIG_REF_NAME==audio_mixer_project_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/audio_mixer_project/ip/audio_mixer_project_rst_ps7_0_100M_0/audio_mixer_project_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_mixer_project_rst_ps7_0_100M_0 || ORIG_REF_NAME==audio_mixer_project_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/audio_mixer_project/ip/audio_mixer_project_zed_audio_0_0/audio_mixer_project_zed_audio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_mixer_project_zed_audio_0_0 || ORIG_REF_NAME==audio_mixer_project_zed_audio_0_0} -quiet] -quiet

# IP: bd/audio_mixer_project/ip/audio_mixer_project_xlconstant_0_0/audio_mixer_project_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_mixer_project_xlconstant_0_0 || ORIG_REF_NAME==audio_mixer_project_xlconstant_0_0} -quiet] -quiet

# IP: bd/audio_mixer_project/ip/audio_mixer_project_FILTER_IIR_0_0/audio_mixer_project_FILTER_IIR_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_mixer_project_FILTER_IIR_0_0 || ORIG_REF_NAME==audio_mixer_project_FILTER_IIR_0_0} -quiet] -quiet

# IP: bd/audio_mixer_project/ip/audio_mixer_project_Volume_Pregain_0_0/audio_mixer_project_Volume_Pregain_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_mixer_project_Volume_Pregain_0_0 || ORIG_REF_NAME==audio_mixer_project_Volume_Pregain_0_0} -quiet] -quiet

# IP: bd/audio_mixer_project/ip/audio_mixer_project_xlconcat_0_0/audio_mixer_project_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_mixer_project_xlconcat_0_0 || ORIG_REF_NAME==audio_mixer_project_xlconcat_0_0} -quiet] -quiet

# IP: bd/audio_mixer_project/ip/audio_mixer_project_mixer_0_0/audio_mixer_project_mixer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_mixer_project_mixer_0_0 || ORIG_REF_NAME==audio_mixer_project_mixer_0_0} -quiet] -quiet

# IP: bd/audio_mixer_project/ip/audio_mixer_project_xbar_0/audio_mixer_project_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_mixer_project_xbar_0 || ORIG_REF_NAME==audio_mixer_project_xbar_0} -quiet] -quiet

# IP: bd/audio_mixer_project/ip/audio_mixer_project_ZedboardOLED_0_0/audio_mixer_project_ZedboardOLED_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_mixer_project_ZedboardOLED_0_0 || ORIG_REF_NAME==audio_mixer_project_ZedboardOLED_0_0} -quiet] -quiet

# IP: bd/audio_mixer_project/ip/audio_mixer_project_FILTER_IIR_1_0/audio_mixer_project_FILTER_IIR_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_mixer_project_FILTER_IIR_1_0 || ORIG_REF_NAME==audio_mixer_project_FILTER_IIR_1_0} -quiet] -quiet

# IP: bd/audio_mixer_project/ip/audio_mixer_project_axi_to_audio_0_0/audio_mixer_project_axi_to_audio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_mixer_project_axi_to_audio_0_0 || ORIG_REF_NAME==audio_mixer_project_axi_to_audio_0_0} -quiet] -quiet

# IP: bd/audio_mixer_project/ip/audio_mixer_project_Volume_Pregain_1_1/audio_mixer_project_Volume_Pregain_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_mixer_project_Volume_Pregain_1_1 || ORIG_REF_NAME==audio_mixer_project_Volume_Pregain_1_1} -quiet] -quiet

# IP: bd/audio_mixer_project/ip/audio_mixer_project_pmod_controller_0_0/audio_mixer_project_pmod_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_mixer_project_pmod_controller_0_0 || ORIG_REF_NAME==audio_mixer_project_pmod_controller_0_0} -quiet] -quiet

# IP: bd/audio_mixer_project/ip/audio_mixer_project_axi_gpio_1_0/audio_mixer_project_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_mixer_project_axi_gpio_1_0 || ORIG_REF_NAME==audio_mixer_project_axi_gpio_1_0} -quiet] -quiet

# IP: bd/audio_mixer_project/ip/audio_mixer_project_auto_pc_0/audio_mixer_project_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_mixer_project_auto_pc_0 || ORIG_REF_NAME==audio_mixer_project_auto_pc_0} -quiet] -quiet

# XDC: bd/audio_mixer_project/audio_mixer_project_ooc.xdc
