set_property IOSTANDARD LVCMOS33 [get_ports Rotary_a]
set_property IOSTANDARD LVCMOS33 [get_ports Rotary_b]
set_property IOSTANDARD LVCMOS33 [get_ports Button]
set_property IOSTANDARD LVCMOS33 [get_ports Switch]
set_property PACKAGE_PIN Y10 [get_ports Button]
set_property PACKAGE_PIN Y11 [get_ports Rotary_a]
set_property PACKAGE_PIN AA11 [get_ports Rotary_b]
set_property PACKAGE_PIN AA9 [get_ports Switch]